export const emotions = [
  { id:"calm", title:"Спокойствие", group:"Тихие", detail:"Мягкая улыбка и ровный взгляд." },
  { id:"joy", title:"Радость", group:"Светлые", detail:"Широкая улыбка, приподнятые щёки." },
  { id:"curious", title:"Любопытство", group:"Светлые", detail:"Одна бровь выше, взгляд следует за предметом." },
  { id:"focused", title:"Сосредоточенность", group:"Рабочие", detail:"Прищур и спокойный взгляд вниз. Без резких взмахов." },
  { id:"worried", title:"Забота", group:"Рабочие", detail:"Домиком брови и сочувственная мимика." },
  { id:"sleepy", title:"Сонливость", group:"Тихие", detail:"Полузакрытые глаза и короткий зевок." },
  { id:"surprised", title:"Удивление", group:"Яркие", detail:"Круглые глаза и рот буквой «о»." },
  { id:"proud", title:"Гордость", group:"Яркие", detail:"Уверенный прищур и довольная улыбка." },
  { id:"shy", title:"Смущение", group:"Тихие", detail:"Взгляд в сторону и румянец." },
  { id:"sad", title:"Грусть", group:"Тихие", detail:"Опущенные веки и маленькая грустная дуга." },
  { id:"determined", title:"Решимость", group:"Рабочие", detail:"Брови собраны, взгляд прямой." },
  { id:"affectionate", title:"Нежность", group:"Светлые", detail:"Тёплый взгляд и мягкая улыбка." },
];

export const actions = [
  { id:"idle", title:"Дышит и оглядывается", group:"Повседневные", detail:"Маленькие паузы, дыхание и живые крылья." },
  { id:"wave", title:"Приветствует", group:"Общение", detail:"Поднимает руку и машет, не теряя равновесия." },
  { id:"nod", title:"Кивает", group:"Общение", detail:"Короткое понятное «я услышал»." },
  { id:"peek", title:"Выглядывает", group:"Общение", detail:"Наклоняется и выглядывает из-за края." },
  { id:"point", title:"Показывает", group:"Общение", detail:"Мягко указывает на важную вещь." },
  { id:"offer", title:"Протягивает", group:"Общение", detail:"Показывает предмет зрителю." },
  { id:"focus", title:"Работает спокойно", group:"Работа", detail:"Держит блокнот, читает и делает редкие пометки.", prop:"notebook" },
  { id:"read", title:"Читает", group:"Работа", detail:"Переводит взгляд по страницам.", prop:"book" },
  { id:"write", title:"Записывает", group:"Работа", detail:"Неспешно ведёт карандаш по листу.", prop:"pencil" },
  { id:"think", title:"Размышляет", group:"Работа", detail:"Смотрит вверх, рядом появляется идея.", prop:"gear" },
  { id:"listen", title:"Слушает", group:"Голос", detail:"Замирает и поворачивается к голосу." },
  { id:"speak", title:"Говорит", group:"Голос", detail:"Ритм рта и жестов следует за репликой." },
  { id:"reassure", title:"Поддерживает", group:"Общение", detail:"Небольшой наклон и открытые ладони.", prop:"heart" },
  { id:"celebrate", title:"Празднует", group:"Игра", detail:"Подпрыгивает и раскрывает крылья.", prop:"star" },
  { id:"dance", title:"Танцует", group:"Игра", detail:"Переступает и качается в ритме." },
  { id:"float", title:"Парит", group:"Игра", detail:"Приподнимается над пьедесталом." },
  { id:"stretch", title:"Потягивается", group:"Отдых", detail:"Медленно поднимает обе руки." },
  { id:"sip", title:"Пьёт чай", group:"Отдых", detail:"Подносит кружку и делает паузу.", prop:"mug" },
  { id:"sleep", title:"Дремлет", group:"Отдых", detail:"Засыпает на месте, покачивая головой.", prop:"pillow" },
];

export const props = [
  { id:"book", title:"Книга", group:"Рабочий стол", detail:"Раскрывает страницы и читает.", icon:"▰" },
  { id:"notebook", title:"Блокнот", group:"Рабочий стол", detail:"Тихая работа и короткие пометки.", icon:"▤" },
  { id:"pencil", title:"Карандаш", group:"Рабочий стол", detail:"Неспешно пишет строки в блокноте.", icon:"✎" },
  { id:"tablet", title:"Планшет", group:"Рабочий стол", detail:"Показывает список задач.", icon:"▣" },
  { id:"laptop", title:"Ноутбук", group:"Рабочий стол", detail:"Печатает за маленьким столом, экран светит в лицо.", icon:"▱" },
  { id:"calendar", title:"Календарь", group:"Рабочий стол", detail:"Напоминает о времени.", icon:"▦" },
  { id:"scroll", title:"Свиток", group:"Рабочий стол", detail:"Несёт длинную историю.", icon:"▥" },
  { id:"map", title:"Карта", group:"Рабочий стол", detail:"Ищет путь к следующему шагу.", icon:"◇" },
  { id:"hourglass", title:"Песочные часы", group:"Время и идеи", detail:"Тихий знак ожидания.", icon:"⧗" },
  { id:"clock", title:"Часы", group:"Время и идеи", detail:"Время для паузы или срока.", icon:"◷" },
  { id:"compass", title:"Компас", group:"Время и идеи", detail:"Помогает выбрать направление.", icon:"⌖" },
  { id:"magnifier", title:"Лупа", group:"Время и идеи", detail:"Рассматривает деталь.", icon:"⌕" },
  { id:"gear", title:"Шестерня", group:"Время и идеи", detail:"Небольшая мысль в движении.", icon:"⚙" },
  { id:"key", title:"Ключ", group:"Время и идеи", detail:"Находит способ открыть задачу.", icon:"⚿" },
  { id:"wrench", title:"Гаечный ключ", group:"Время и идеи", detail:"Аккуратно чинит то, что сломалось.", icon:"⌑" },
  { id:"crystal", title:"Кристалл", group:"Время и идеи", detail:"Собирает идею в одну точку.", icon:"◈" },
  { id:"mug", title:"Кружка", group:"Уют", detail:"Тёплый чай в спокойную минуту.", icon:"◡" },
  { id:"teapot", title:"Чайник", group:"Уют", detail:"Время для маленького перерыва.", icon:"♨" },
  { id:"plant", title:"Росток", group:"Уют", detail:"Что-то хорошее растёт.", icon:"♧" },
  { id:"lantern", title:"Фонарь", group:"Уют", detail:"Небольшой свет рядом.", icon:"✦" },
  { id:"pillow", title:"Подушка", group:"Уют", detail:"Место для тихого сна.", icon:"▢" },
  { id:"blanket", title:"Плед", group:"Уют", detail:"Можно выдохнуть и согреться.", icon:"▧" },
  { id:"palette", title:"Палитра", group:"Творчество", detail:"Выбирает цвет для идеи.", icon:"◕" },
  { id:"brush", title:"Кисть", group:"Творчество", detail:"Рисует плавную линию.", icon:"╱" },
  { id:"camera", title:"Камера", group:"Творчество", detail:"Ловит момент.", icon:"▣" },
  { id:"music", title:"Нота", group:"Творчество", detail:"Маленький музыкальный мотив.", icon:"♫" },
  { id:"star", title:"Звезда", group:"Творчество", detail:"Искорка для завершённого дела.", icon:"✦" },
  { id:"microphone", title:"Микрофон", group:"Связь", detail:"Слушает или говорит.", icon:"♩" },
  { id:"headphones", title:"Наушники", group:"Связь", detail:"Внимательно слушает.", icon:"◡" },
  { id:"envelope", title:"Письмо", group:"Связь", detail:"Приносит добрую весть.", icon:"✉" },
  { id:"plane", title:"Бумажный самолёт", group:"Связь", detail:"Сообщение летит по кругу, маскот следит за ним.", icon:"➤" },
  { id:"bubble", title:"Облако речи", group:"Связь", detail:"Говорит без спешки.", icon:"◌" },
  { id:"bell", title:"Колокольчик", group:"Связь", detail:"Тихо зовёт внимание.", icon:"♧" },
  { id:"gift", title:"Подарок", group:"Праздник", detail:"Небольшой сюрприз.", icon:"▣" },
  { id:"balloon", title:"Шарик", group:"Праздник", detail:"Лёгкое настроение.", icon:"◯" },
  { id:"trophy", title:"Кубок", group:"Праздник", detail:"Отмечает результат.", icon:"♛" },
  { id:"heart", title:"Сердце", group:"Праздник", detail:"Знак заботы.", icon:"♥" },
  { id:"shield", title:"Щит", group:"Праздник", detail:"Ощущение безопасности.", icon:"⬡" },
];

export const scenarios = [
  { id:"hello", title:"Встреча", group:"Общение", detail:"Тихое приветствие без навязчивости.", emotion:"joy", action:"wave", prop:"", line:"Привет. Я рядом, если понадоблюсь." },
  { id:"working", title:"Работа идёт", group:"Работа", detail:"Занят своим делом, не отвлекает.", emotion:"focused", action:"focus", prop:"notebook", line:"Я присмотрю за ходом работы." },
  { id:"waiting", title:"Ждёт ответа", group:"Работа", detail:"Подсказывает, что нужен следующий шаг.", emotion:"curious", action:"listen", prop:"hourglass", line:"Тут нужен твой ответ." },
  { id:"done", title:"Готово", group:"Работа", detail:"Радуется завершению дела.", emotion:"proud", action:"celebrate", prop:"star", line:"Готово! Отличная работа." },
  { id:"problem", title:"Нужно внимание", group:"Работа", detail:"Сообщает о проблеме без тревожного спектакля.", emotion:"worried", action:"reassure", prop:"lantern", line:"Давай спокойно посмотрим, что случилось." },
  { id:"idea", title:"Появилась идея", group:"Творчество", detail:"Думает, затем показывает находку.", emotion:"surprised", action:"think", prop:"gear", line:"Кажется, есть идея." },
  { id:"break", title:"Перерыв", group:"Уют", detail:"Не требует внимания и предлагает паузу.", emotion:"calm", action:"sip", prop:"mug", line:"Можно немного выдохнуть." },
  { id:"night", title:"Поздний час", group:"Уют", detail:"Затихает и бережёт спокойствие.", emotion:"sleepy", action:"sleep", prop:"pillow", line:"Я побуду тихо." },
  { id:"voice_listen", title:"Голос · слушает", group:"Голос", detail:"Сцена вместо большой кнопки микрофона.", emotion:"curious", action:"listen", prop:"microphone", line:"Слушаю тебя." },
  { id:"voice_reply", title:"Голос · отвечает", group:"Голос", detail:"Мимика и свет подстраиваются под ответ.", emotion:"affectionate", action:"speak", prop:"bubble", line:"Вот что я думаю." },
];

export const mascots = [
  { id:"daedalus", title:"Daedalus", detail:"Главный маскот · бронзовый корпус и светящееся сердце" },
  { id:"chibi", title:"Маленький помощник", detail:"Тот же язык движений в компактном персонаже" },
  { id:"head", title:"Летающая голова", detail:"Лёгкая версия для тесных поверхностей" },
];

export const byId = (items, id) => items.find((item) => item.id === id);
